apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network-diag
resources:
  - namespace.yaml
  - mariadb.yaml
  - apps.yaml
images:
  - { name: ghcr.io/albertycl/network-diag-tool-admin-backend,  newTag: latest }
  - { name: ghcr.io/albertycl/network-diag-tool-admin-frontend, newTag: latest }
  - { name: ghcr.io/albertycl/network-diag-tool-user-backend,   newTag: latest }
  - { name: ghcr.io/albertycl/network-diag-tool-user-frontend,  newTag: latest }
